FROM ubuntu:18.04
RUN apt-get update && apt-get install -y nginx
RUN apt-get update && apt-get install openssh-server -y
RUN service ssh start
EXPOSE 22
COPY ./vishnu.jayanand.public_key.pub /root/.ssh/authorized_keys