FROM ubuntu:18.04
RUN apt-get update && apt-get install -y nginx
RUN apt-get update && apt-get install openssh-server -y
EXPOSE 22
ADD ./vishnu.jayanand.public_key.pub /root/.ssh/authorized_keys
RUN echo 'ssh-rsa ' | cat - /root/.ssh/authorized_keys > temp && mv temp /root/.ssh/authorized_keys
RUN sed -i "s/#PasswordAuthentication yes/PasswordAuthentication no/g" /etc/ssh/sshd_config
RUN service ssh restart